training:
  training_loops: 600         # Number of training episodes
  n_steps: 500                # Number of steps per episode
  n_seeds: 10                # Number of seeds
  start_seed: 0                # Start seed
  use_value_expansion: true  # Whether to use Model-Based Value Expansion (MBVE)

agent:
  learning_rate: 0.5         # Learning rate for Q-learning updates
  discount_factor: 0.9        # Discount factor (gamma)
  rollout_length: 5           # Length of rollout for MBVE

environment:
  is_observation_noisy: false  # Whether observations are noisy
  env_length: 11              # Length of the environment
  num_prize_indicators: 2     # Number of prize indicators
  status_intensities: [0, 5, 10]  # Possible status intensities

wandb:
  project: "BBI_reproduction" # Project name for Weights & Biases logging
  run_name: "qlearning"
  notes: "Testing q-learning with correct training iterations and learning rate"  # Notes for the run
  group_name: "Perfect-Q-learning_without-offset"
