training:
  training_loops: 600         # Number of training episodes
  n_steps: 500                # Number of steps per episode
  n_seeds: 20                  # Number of seeds
  start_seed: 0               # Start seed

agent:
  learning_rate: 0.05         # Learning rate for Q-learning updates
  gamma: 0.9                  # Discount factor (gamma)
  max_horizon: 1              # Length of rollout for MBVE

environment_id: "bbi/goRight-v0"

wandb:
  project: "BBI_reproduction" # Project name for Weights & Biases logging
  notes: "Testing codebase simplification refact"  # Notes for the run
  group_name: "goright_refactor_test"
