[project]
name = "sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.2",
    "numpy>=1.26.4",
    "gymnasium[classic-control]>=0.29.1",
    "tdm>=0.1.0",
    "tqdm>=4.66.5",
    "matplotlib>=3.9.2",
    "pyinstrument>=4.7.3",
    "wandb>=0.18.1",
    "cython>=3.0.11",
]
