training:
  training_loops: 600         # Number of training episodes
  n_steps: 500                # Number of steps per episode
  n_seeds: 25                  # Number of seeds
  start_seed: 1               # Start seed

agent:
  learning_rate: 0.1         # Learning rate for Q-learning updates
  discount: 0.9                  # Discount factor (gamma)
  max_horizon: 5              # Length of rollout for MBVE

environment_id: "bbi/goRight-v0"
model_id: "perfect"

wandb:
  project: "BBI_reproduction" # Project name for Weights & Biases logging
  notes: "Perfect model unselective planning with GoRight environment"  # Notes for the run
  group_name: "goright_perfect_v2"
