training:
  training_loops: 600         # Number of training episodes
  n_steps: 500                # Number of steps per episode
  n_seeds: 7                  # Number of seeds
  start_seed: 3               # Start seed

agent:
  learning_rate: 0.1          # Learning rate for Q-learning updates
  discount: 0.9                  # Discount factor (gamma)
  max_horizon: 5              # Length of rollout for MBVE
  tau: 1.0

environment_id: "bbi/goRight-v0"
model_id: "bbi_linear"

wandb:
  project: "BBI_reproduction" # Project name for Weights & Biases logging
  notes: "BBI with GoRight environment with linear function approximation"  # Notes for the run
  group_name: "goright_bbi_linear"
