training:
  training_loops: 600         # Number of training episodes
  n_steps: 500                # Number of steps per episode
  n_seeds: 5                  # Number of seeds
  start_seed: 0               # Start seed

agent:
  learning_rate: 0.1         # Learning rate for Q-learning updates
  discount: 0.9                  # Discount factor (gamma)
  max_horizon: 2              # Length of rollout for MBVE

environment_id: "bbi/goRight-v0"

model_id: "expected"

wandb:
  project: "BBI_reproduction" # Project name for Weights & Biases logging
  notes: "Expectation model unselective planning with GoRight environment with h = 2. Included initializations cases."  # Notes for the run
  group_name: "goright_expected_h2"
